### PR TITLE
add unittest to cp2k restart

### PR DESCRIPTION
**Pull request by felix5572**
add unittest to cp2k restart

### CODE REVIEW

**Comment by felix5572** [comment]
@dmh1998dmh 
please take a look?
I add a unittest to cp2k restart.

and I think redefine a function may not be a good idea(even if with different decoreator)

**Comment by dmh1998dmh** [comment]
> unittest

Thanks, i am working on unittest.

**Comment by dmh1998dmh** [comment]
> @dmh1998dmh
> please take a look?
> I add a unittest to cp2k restart.
> 
> and I think redefine a function may not be a good idea(even if with different decoreator)

I not famililar with developing a Python project. Is unittest for auto test transfoming aimd_output files in tests/cp2k/restart_aimd (I created)?

**Comment by felix5572** [comment]
Yes.  I have implemented the unittest for the files in tests/cp2k/restart_aimd.

The unittest can guarantee that the restart_flag work as expected

the unittest is located at tests/test_cp2k_aimd_output.py

**Comment by dmh1998dmh** [comment]
Thanks. It works fine.

**Pull request merged**
